eStore/Controllers/LogoutController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eStore.Controllers
{
    public class LogoutController : Controller
    {
        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Login");
        }
    }
}

eStore/Controllers/MemberController.cs
using BusinessObject;
using DataAccess.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eStore.Controllers
{
    public class MemberController : Controller
    {
        IMemberRepository memberRepository;
        // GET: MemberController
        public ActionResult Index()
        {
            memberRepository = new MemberRepository();
            string role = HttpContext.Session.GetString("Role");
            if (role.Equals("AD"))
            {
                var model = memberRepository.GetMembersList();
                return View(model);
            }
            else
            {
                TblMember member = HttpContext.Session.GetComplexData<TblMember>("account");
                var model = memberRepository.GetMembersListByUser(member.MemberId);
                return View(model);
            }
            
        }

        // GET: MemberController/Details/5
        public ActionResult Details(int? id)
        {
            memberRepository = new MemberRepository();
            if (id == null)
            {
                return NotFound();
            }
            var member = memberRepository.GetMembersById(id.Value);
            if (member == null)
            {
                return NotFound();
            }
            return View(member);
        }

        [Authorize(Roles = "Admin")]
        // GET: MemberController/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        // POST: MemberController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TblMember member)
        {
            memberRepository = new MemberRepository();
            try
            {
                if (ModelState.IsValid)
                {
                    memberRepository.AddNew(member);
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
        }

        // GET: MemberController/Edit/5
        public ActionResult Edit(int? id)
        {
            memberRepository = new MemberRepository();
            if (id == null)
            {
                return NotFound();
            }
            var member = memberRepository.GetMembersById(id.Value);
            if (member == null)
            {
                return NotFound();
            }
            return View(member);
        }

        // POST: MemberController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int MemberId, TblMember member)
        {
            memberRepository = new MemberRepository();
            try
            {
                if (MemberId != member.MemberId)
                {
                    return NotFound();
                }
                if (ModelState.IsValid)
                {
                    memberRepository.Update(member);
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
        }

        // GET: MemberController/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            memberRepository = new MemberRepository();
            if (id == null)
            {
                return NotFound();
            }
            var member = memberRepository.GetMembersById(id.Value);
            if (member == null)
            {
                return NotFound();
            }
            return View(member);
        }

        // POST: MemberController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int MemberId)
        {
            memberRepository = new MemberRepository();
            try
            {
                memberRepository.Remove(MemberId);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
        }
    }
}

eStore/Controllers/OrderController.cs
using BusinessObject;
using DataAccess.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eStore.Controllers
{
    public class OrderController : Controller
    {
        IOrderRepository orderRepository;
        // GET: OrderController
        [Authorize(Roles = "Admin,User")]
        public ActionResult Index()
        {
            orderRepository = new OrderRepository();
            TblMember member = HttpContext.Session.GetComplexData<TblMember>("account");
            string role = HttpContext.Session.GetString("Role");
            if (member != null)
            {
                if (role.Equals("AD"))
                {
                    var model = orderRepository.GetOrdersList();
                    return View(model);
                }
                else
                {
                    var model = orderRepository.GetOrdersListByMember(member.MemberId);
                    return View(model);
                }
            }
            else
            {
                return NotFound();
            }
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Statistic(DateTime? start, DateTime? end)
        {
            orderRepository = new OrderRepository();
            List<TblOrder> orders = orderRepository.MakeReportStatistic(start.Value, end.Value).ToList();
            var order = from c in orders
                         group c by c.OrderDate into grp
                         where grp.Count() > 0
                         select new { OrderDate = grp.Key, Total = grp.Count() };
            var statistic = from o in order
                            orderby o.Total descending
                            select o;
            List<String> orderDates = new List<string>();
            List<int> totals = new List<int>();
            foreach (var s in statistic)
            {
                orderDates.Add(s.OrderDate.ToShortDateString());
                totals.Add(s.Total);
            }
            ViewBag.orderDates = orderDates;
            ViewBag.totals = totals;
            return View();
        }

        // GET: OrderController/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            orderRepository = new OrderRepository();
            if (id == null)
            {
                return NotFound();
            }
            var order = orderRepository.GetOrderById(id.Value);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        // GET: OrderController/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            IMemberRepository memberRepository = new MemberRepository();
            ViewBag.MemberId = memberRepository.GetMembersList().Select(x => new SelectListItem()
            {
                Text = x.Email,
                Value = x.MemberId.ToString()
            });
            return View();
        }

        // POST: OrderController/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TblOrder order)
        {
            IMemberRepository memberRepository = new MemberRepository();
            orderRepository = new OrderRepository();
            try
            {
                if (ModelState.IsValid)
                {
                    orderRepository.AddNew(order);
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.MemberId = memberRepository.GetMembersList().Select(x => new SelectListItem()
                {
                    Text = x.Email,
                    Value = x.MemberId.ToString()
                });
                ViewBag.Message = ex.Message;
                return View();
            }
        }

        // GET: OrderController/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            orderRepository = new OrderRepository();
            IMemberRepository memberRepository = new MemberRepository();
            ViewBag.MemberId = memberRepository.GetMembersList().Select(x => new SelectListItem()
            {
                Text = x.Email,
                Value = x.MemberId.ToString()
            });
            if (id == null)
            {
                return NotFound();
            }
            var order = orderRepository.GetOrderById(id.Value);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        // POST: OrderController/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int OrderId, TblOrder order)
        {
            IMemberRepository memberRepository = new MemberRepository();
            orderRepository = new OrderRepository();
            try
            {
                if (OrderId != order.OrderId)
                {
                    return NotFound();
                }
                if (ModelState.IsValid)
                {
                    orderRepository.Update(order);
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.MemberId = memberRepository.GetMembersList().Select(x => new SelectListItem()
                {
                    Text = x.Email,
                    Value = x.MemberId.ToString()
                });
                ViewBag.Message = ex.Message;
                return View();
            }
        }

        // GET: OrderController/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            orderRepository = new OrderRepository();
            if (id == null)
            {
                return NotFound();
            }
            var order = orderRepository.GetOrderById(id.Value);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        // POST: OrderController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int OrderId)
        {
            orderRepository = new OrderRepository();
            try
            {
                orderRepository.Remove(OrderId);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
        }
    }
}

eStore/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">eStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @{
        if (@Accessor.HttpContext.Session.GetString("Role") == null)
        {
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        }
        else
        {
            <div class="wrapper">
                <!-- Sidebar  -->
                <nav id="sidebar">
                    <div class="sidebar-header">
                        <h3>E-STORE</h3>
                    </div>

                    <ul class="list-unstyled components">
                        <li class="active">
                            <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Shoping</a>
                            <ul class="collapse list-unstyled" id="homeSubmenu">
                                <li>
                                    <a asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Administration</a>
                            <ul class="collapse list-unstyled" id="pageSubmenu">
                                <li>
                                    <a asp-area="" asp-controller="Member" asp-action="Index">Members</a>
                                </li>
                                <li>
                                    <a asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Logout" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </nav>

                <!-- Page Content  -->
                <div id="content">

                    <div style="margin-top:-50px; margin-left: -10px">
                        <div class="container-fluid">

                            <button type="button" id="sidebarCollapse" class="btn btn-info">
                                <i class="bi bi-justify-left"></i>
                            </button>
                            <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                                <i class="bi bi-justify"></i>
                            </button>
                        </div>
                    </div>
                    @RenderBody()
                </div>
            </div>
        }
    }


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - eStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>